### PR TITLE
Flush batch after shutdown

### LINKED ISSUE #51: BigQuery output plugin doesn't load all rows into table from source
Hello,

This is w.r.t to my discussion post in logstash forum - https://discuss.elastic.co/t/logstash-es-to-bigquery-doesnt-load-all-rows-into-bigquery/190114

- Version: Logstash 7.1.1
- Operating System: Mac 
- Steps to Reproduce:
Ran logstash job for specified config file with default parameters

**Background:**
Long story short - My logstash job runs successfully but doesn't load all the rows into bigquery table from source.  I analyzed that my input plugin and filter plugin do not filter out valid records. As mentioned in forum post, the total number of records in source is 11437 whereas the total number of records committed using default setting is 11392, and the number of records that haven't been loaded is 45. By default, the batch_size is 128; I changed this setting and other settings provided but somehow couldn't load all the data from source.

I observed that the logstash loads data in multiples of the batch size specified (11392 is 89*128) and "drops" the last bunch which are left out by batch processing( 11437 - 11392 = 45*). This happened not only with the table specified in the forum but also with several others.

**Fix:**
By reverse engineering the logstash output log, I figured out that the method "enqueue" in "Batcher.rb" gem works in tandem with method "publish" in "google_bigquery.rb" gem to stream incoming records to bigquery table. Depending on the "[batch size](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-google_bigquery.html#plugins-outputs-google_bigquery-batch_size)", the plugin would group incoming records into batches and insert them into bigquery tables.

In order to ensure that all records are processed, I did the following:

1. Passed in the total number of records to be processed as a parameter to output plugin.
2. Calculated the total number of records processed in batches.
3. After all the batches were processed, I calculated the difference left out by batch processing and loaded them in one shot.

**Customized code:**

def initialize(max_length, max_bytes)
          @lock = ReentrantReadWriteLock.new
          @max_length = max_length --Passed total number of incoming records to this parameter
          @batch_size = 128 --defined default batch size as 128
          @num_processed_records = 0 --counter to count to total number of records processed by batch
          @max_bytes = max_bytes
          clear
end

def enqueue(message)
          @lock.write_lock.lock

          begin
            is_flush_request = message.nil?

            unless is_flush_request
              @batch_size_bytes += message.length
              @batch << message
              @num_processed_records = @num_processed_records + 1 --row counter
            end

            length_met = @batch.length >= @batch_size
            total_length_met = @max_length - @num_processed_records == 0 --flag to indicate that last bunch left out by batch processing
            size_met = @batch_size_bytes >= @max_bytes

            #is_flush_request || length_met || size_met || total_length_met

            print(@batch.length, "total number of records", @num_processed_records, " ", length_met, " ", size_met, " ", total_length_met, "\n")

            if length_met || size_met || total_length_met
              orig = @batch
              clear

              yield(orig) if block_given?
              return orig
            end

            nil

          ensure
            @lock.write_lock.unlock
          end
        end

**Fixed Batcher.rb Code file:**
[batcher.txt](https://github.com/logstash-plugins/logstash-output-google_bigquery/files/3413351/batcher.txt)

**Log output:**

[Log File.txt](https://github.com/logstash-plugins/logstash-output-google_bigquery/files/3413345/Log.File.txt)

I can demo this to you in case needed. I believe sometimes there is an issue counting the number of records processed. Please let me know.

### PR DESCRIPTION
**Pull request by robbavey**
Fixes issue where when Logstash shuts down, even during a clean shutdown,
this plugin will not flush any messages residing in the buffer,
potentially resulting in data loss.

Fixes #51

### CODE REVIEW

File: lib/logstash/outputs/google_bigquery.rb [hunk 1]
```diff
@@ -181,6 +182,7 @@ def register
     @schema = LogStash::Outputs::BigQuery::Schema.parse_csv_or_json @csv_schema, @json_schema
     @bq_client = LogStash::Outputs::BigQuery::StreamingClient.new @json_key_file, @project_id, @logger
     @batcher = LogStash::Outputs::BigQuery::Batcher.new @batch_size, @batch_size_bytes
+    @stopping = Concurrent::AtomicBoolean.new
```
Comment (colinsurprenant) [inline lib/logstash/outputs/google_bigquery.rb]: nitpick: I suggest to pass `false`, even though it is the default, to make it explicit that we start in the `false` state - it avoid someone looking at the code wonders if the default it `true` or `false`.
```suggestion
    @stopping = Concurrent::AtomicBoolean.new(false)
```

File: lib/logstash/outputs/google_bigquery.rb [hunk 2]
```diff
@@ -274,11 +276,21 @@ def write_to_errors_file(messages, table)
 
   def init_batcher_flush_thread
     @flush_thread = Thread.new do
-      loop do
+      until stopping?
         sleep @flush_interval_secs
```
Comment (colinsurprenant) [inline lib/logstash/outputs/google_bigquery.rb]: to avoid `sleep` stalling a shutdown, this could be used
```
Stud.stoppable_sleep(@flush_interval_secs) { stopping? }
```

File: lib/logstash/outputs/google_bigquery.rb [hunk 3]
```diff
@@ -274,11 +276,21 @@ def write_to_errors_file(messages, table)
 
   def init_batcher_flush_thread
     @flush_thread = Thread.new do
-      loop do
-        sleep @flush_interval_secs
+      until stopping?
```
Comment (yaauie) [inline lib/logstash/outputs/google_bigquery.rb]: I can see a narrow race here, in which the pipeline receives a shutdown signal after this output has begun flushing, which would cause it to not enter this loop again and therefore not receive a final flush.

Comment (robbavey) [reply lib/logstash/outputs/google_bigquery.rb]: Good catch @yaauie

Comment (colinsurprenant) [reply lib/logstash/outputs/google_bigquery.rb]: 🦅 eyes

**Comment by robbavey** [comment]
Thanks @yaauie @colinsurprenant!
